/**
 * Controlled execution boundary for a reviewed staged-ingestion artifact.
 * It is intentionally separate from Commander and accepts no arbitrary input.
 */
declare const require: (moduleName: string) => any;
declare const process: { argv: readonly string[]; cwd(): string; env: Record<string, string | undefined>; exit(code?: number): void };

const fs = require("fs");
const path = require("path");

import {
  loadTigerGraphMcpConfigurationFromEnvironment,
  StdioTigerGraphMcpTransport,
  type McpToolTransport,
} from "../packages/tigergraph/src/mcp-commander-tool-client.js";

function loadLocalEnvironment(): void {
  const envPath = path.resolve(process.cwd(), ".env");
  if (!fs.existsSync(envPath)) return;
  for (const line of fs.readFileSync(envPath, "utf8").split(/\r?\n/)) {
    const match = line.match(/^([A-Za-z_][A-Za-z0-9_]*)=(.*)$/);
    if (match && !process.env[match[1]]) process.env[match[1]] = match[2].trim().replace(/^['"]|['"]$/g, "");
  }
}

function parseSuccess(response: unknown): boolean {
  const envelope = response as { content?: readonly { text?: unknown }[]; isError?: boolean };
  if (envelope?.isError) return false;
  const text = envelope?.content?.map((item) => typeof item.text === "string" ? item.text : "").find(Boolean);
  const fenced = text?.match(/```json\s*([\s\S]*?)```/i)?.[1];
  try {
    const parsed = JSON.parse((fenced ?? text ?? "").trim()) as { success?: unknown; data?: { result?: unknown } };
    return parsed.success === true && typeof parsed.data?.result === "string" && !/^Error:/i.test(parsed.data.result);
  } catch {
    return false;
  }
}

function validateArtifact(gsql: string, manifest: Record<string, unknown>): void {
  const selection = manifest.selection as { benchmark_transaction_ids?: unknown; case_limit?: unknown } | undefined;
  const ids = selection?.benchmark_transaction_ids;
  if (!Array.isArray(ids) || ids.length !== 20 || selection?.case_limit !== 0) {
    throw new Error("artifact_does_not_match_20_case_coverage_contract");
  }
  if (!gsql.startsWith("// Generated by scripts/staged_ingestion.py") || !gsql.includes("INTERPRET QUERY () FOR GRAPH FraudCommand")) {
    throw new Error("unrecognized_ingestion_artifact");
  }
  if (/\b(DROP|CREATE|DELETE|UPDATE|ALTER|INSTALL)\b/i.test(gsql)) {
    throw new Error("disallowed_gsql_operation");
  }
  if (!/\bINSERT INTO Transaction\b/.test(gsql) || (gsql.match(/\bINSERT INTO Transaction\b/g) ?? []).length !== 20) {
    throw new Error("unexpected_transaction_coverage");
  }
}

export async function executeCoverageArtifact(transport: McpToolTransport, artifactDirectory: string): Promise<void> {
  const gsql = fs.readFileSync(path.join(artifactDirectory, "stage1.gsql"), "utf8");
  const manifest = JSON.parse(fs.readFileSync(path.join(artifactDirectory, "manifest.json"), "utf8"));
  validateArtifact(gsql, manifest);
  const response = await transport.callTool({
    name: "tigergraph__gsql",
    // Savanna MCP opens a fresh GSQL session for each call. Graph name metadata
    // alone does not select it for INTERPRET QUERY execution.
    arguments: { graph_name: "FraudCommand", command: `USE GRAPH FraudCommand\n${gsql}` },
  });
  if (!parseSuccess(response)) throw new Error("live_staged_ingestion_rejected");
}

async function main(): Promise<void> {
  const argument = process.argv.find((value) => value.startsWith("--artifact-dir="));
  const artifactDirectory = path.resolve(process.cwd(), argument?.slice("--artifact-dir=".length) ?? "artifacts/benchmark_coverage_ingestion");
  loadLocalEnvironment();
  await executeCoverageArtifact(new StdioTigerGraphMcpTransport(loadTigerGraphMcpConfigurationFromEnvironment()), artifactDirectory);
  console.log(JSON.stringify({ mode: "LIVE", status: "PASS", operation: "benchmark_coverage_ingestion" }));
}

main().catch((error: Error) => {
  console.error(JSON.stringify({ mode: "LIVE", status: "FAIL", error: error.message }));
  process.exit(1);
});
